env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
plugins:
  - react
  - jsx-a11y
rules: 
  quotes: 0
overrides:
  - files:
      - '*.tsx'
    rules:
      '@typescript-eslint/explicit-function-return-type': 'off'
