extends:
  - 'markuplint:recommended'
parser:
  "\\.tsx$": '@markuplint/jsx-parser'
specs:
  "\\.tsx$": '@markuplint/react-spec'
rules:
  invalid-attr:
    options:
      allowAttrs:
        - 'hx-boost'
