name: Auto Create Draft PR when No Existing PR for Issue Branch

on:
  push:
    branches:
      - 'issue-*'

jobs:
  create_draft_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Get Issue title
        run: |
          issue_number=${GITHUB_REF#refs/heads/issue-}
          issue_title=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}" | jq -r '.title')
          echo "ISSUE_TITLE=${issue_title}" >> $GITHUB_ENV
          echo "ISSUE_NUMBER=${issue_number}" >> $GITHUB_ENV

      - name: Check existing PR
        run: |
          pr_exists=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref }}" | jq '. | length')
          echo "PR_EXISTS=${pr_exists}" >> $GITHUB_ENV

      - name: Prepare PR body
        run: |
          echo "# 対応ISSUE" > pr_body.md
          echo "" >> pr_body.md
          echo "[\#${{ env.ISSUE_NUMBER }}](https://github.com/${{ github.repository }}/issues/${{ env.ISSUE_NUMBER }})" >> pr_body.md
          echo "" >> pr_body.md
          echo "# 画面URL" >> pr_body.md
          echo "# ...(以下略)..." >> pr_body.md

      - name: Create Draft PR
        if: env.PR_EXISTS == '0'
        run: |
          gh pr create --base main --head ${{ github.ref }} \
          --title "${{ env.ISSUE_TITLE }}" \
          --body-file pr_body.md \
          --draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
